# Generated by Django 3.1.3 on 2020-11-11 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_auto_20201112_0317'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesagge',
            new_name='Message',
        ),
    ]
