# Generated by Django 3.1.3 on 2020-11-16 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0006_auto_20201114_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messagestat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfrom', models.CharField(max_length=20)),
                ('mto', models.CharField(max_length=20)),
                ('mkey', models.CharField(max_length=40, unique=True)),
                ('mstat', models.IntegerField(default=0, max_length=999)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 17, 0, 44, 21, 732321)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 17, 0, 44, 21, 732321)),
        ),
    ]
