# Generated by Django 3.1.3 on 2020-11-16 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0007_auto_20201117_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 17, 0, 46, 57, 154142)),
        ),
        migrations.AlterField(
            model_name='messagestat',
            name='mstat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 17, 0, 46, 57, 154142)),
        ),
    ]
