# Generated by Django 3.1.3 on 2020-11-21 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0009_auto_20201121_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagestat',
            old_name='mfrom',
            new_name='sfrom',
        ),
        migrations.RenameField(
            model_name='messagestat',
            old_name='mkey',
            new_name='skey',
        ),
        migrations.RenameField(
            model_name='messagestat',
            old_name='mstat',
            new_name='sstat',
        ),
        migrations.RenameField(
            model_name='messagestat',
            old_name='mto',
            new_name='sto',
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 5, 29, 58, 677026)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 22, 5, 29, 58, 677026)),
        ),
    ]
