# Generated by Django 3.1.3 on 2020-12-11 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0013_auto_20201211_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 14, 0, 37, 476970)),
        ),
        migrations.AlterField(
            model_name='person',
            name='authenticated',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 14, 0, 37, 475974)),
        ),
    ]
