# Generated by Django 3.1.3 on 2022-03-15 03:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0024_auto_20220314_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 15, 10, 31, 17, 882895)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 15, 10, 31, 17, 882895)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 15, 10, 31, 17, 881898)),
        ),
    ]
