# Generated by Django 3.1.3 on 2022-04-21 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0036_auto_20220421_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appoint2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=20)),
                ('patient', models.CharField(max_length=20)),
                ('appointdate', models.DateField()),
                ('appointtime', models.CharField(max_length=20)),
                ('appointtime2', models.TimeField(default='00:00')),
                ('appointreg', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 21, 8, 46, 3, 619831))),
            ],
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 21, 8, 46, 3, 619831)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 21, 8, 46, 3, 618834)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 21, 8, 46, 3, 618834)),
        ),
    ]
