# Generated by Django 3.1.3 on 2022-04-25 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0057_auto_20220425_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='apptime',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 13, 39, 49, 293112)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 13, 39, 49, 293112)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 13, 39, 49, 293112)),
        ),
        migrations.AlterModelTable(
            name='appoint',
            table='Appoint',
        ),
    ]
