# Generated by Django 3.1.3 on 2022-04-25 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0067_auto_20220425_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='apptime',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 14, 28, 21, 296903)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 14, 28, 21, 296903)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 14, 28, 21, 295907)),
        ),
    ]
