# Generated by Django 3.1.3 on 2022-04-25 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0069_auto_20220425_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='approved',
        ),
        migrations.AddField(
            model_name='appoint',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 14, 49, 9, 482313)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 14, 49, 9, 482313)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 14, 49, 9, 482313)),
        ),
    ]
