# Generated by Django 3.1.3 on 2022-04-25 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0070_auto_20220425_1449'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appoint',
            name='unique appointment',
        ),
        migrations.RemoveConstraint(
            model_name='appoint',
            name='unique_appdoc',
        ),
        migrations.RemoveConstraint(
            model_name='appoint',
            name='unique_apppatient',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 17, 41, 15, 922751)),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 17, 41, 15, 921754)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 17, 41, 15, 921754)),
        ),
    ]
