# Generated by Django 3.1.3 on 2022-04-26 10:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0071_auto_20220425_1741'),
    ]

    operations = [
       migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 26, 17, 31, 38, 6107)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 26, 17, 31, 38, 6107)),
        ),
        migrations.AddConstraint(
            model_name='appoint',
            constraint=models.UniqueConstraint(fields=('doctor', 'patient', 'appointdate', 'appointtime'), name='unique appointment'),
        ),
        migrations.AddConstraint(
            model_name='appoint',
            constraint=models.UniqueConstraint(fields=('doctor', 'appointdate', 'appointtime'), name='unique_appdoc'),
        ),
        migrations.AddConstraint(
            model_name='appoint',
            constraint=models.UniqueConstraint(fields=('patient', 'appointdate', 'appointtime'), name='unique_apppatient'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('name', 'password'), name='unique user'),
        ),
    ]
