# Generated by Django 3.1.3 on 2022-04-26 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0072_auto_20220426_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mfrom', models.CharField(max_length=20)),
                ('mto', models.CharField(max_length=20)),
                ('mcontent', models.CharField(max_length=200)),
                ('msgdate', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 26, 17, 57, 7, 586743))),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='person',
            name='unique user',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 26, 17, 57, 7, 586743)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 26, 17, 57, 7, 586743)),
        ),
    ]
