# Generated by Django 3.1.3 on 2022-04-26 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0073_auto_20220426_1757'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Message',
        # ),
        migrations.RemoveField(
            model_name='person',
            name='authenticated',
        ),
        migrations.RemoveField(
            model_name='person',
            name='crypt',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 26, 17, 58, 5, 396246)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 26, 17, 58, 5, 396246)),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('name', 'password'), name='unique_user'),
        ),
    ]
