# Generated by Django 3.1.3 on 2022-04-26 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0083_auto_20220426_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('typedoctor', models.BooleanField(default=False)),
                ('profile', models.CharField(default='patient', max_length=20)),
                ('registered', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 26, 18, 14, 29, 717221))),
            ],
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 26, 18, 14, 29, 717221)),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('name', 'password'), name='unique_user'),
        ),
    ]
