# Generated by Django 3.1.3 on 2020-11-14 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_auto_20201112_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 14, 16, 44, 25, 307841)),
        ),
    ]
