# Generated by Django 3.1.3 on 2020-11-14 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0005_person_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 14, 20, 57, 23, 354244)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 14, 20, 57, 23, 353214)),
        ),
    ]
