# Generated by Django 3.1.3 on 2020-11-21 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0008_auto_20201117_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 21, 17, 13, 28, 980318)),
        ),
        migrations.AlterField(
            model_name='messagestat',
            name='mkey',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 11, 21, 17, 13, 28, 980318)),
        ),
    ]
