# Generated by Django 3.1.3 on 2020-12-06 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0010_auto_20201122_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dfrom', models.CharField(max_length=20)),
                ('dto', models.CharField(max_length=20)),
                ('mcounter', models.IntegerField()),
                ('ddate', models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 6, 21, 52, 57, 254339))),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 6, 21, 52, 57, 254339)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 6, 21, 52, 57, 254339)),
        ),
    ]
