# Generated by Django 3.1.3 on 2020-12-06 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0011_auto_20201206_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dialog',
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 6, 22, 2, 54, 379141)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 6, 22, 2, 54, 379141)),
        ),
    ]
