# Generated by Django 3.1.3 on 2020-12-11 06:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0012_auto_20201206_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='authenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 13, 52, 17, 744784)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 11, 13, 52, 17, 744784)),
        ),
    ]
