# Generated by Django 3.1.3 on 2020-12-14 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0016_auto_20201214_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='key',
        ),
        migrations.AddField(
            model_name='person',
            name='crypt',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 14, 21, 52, 7, 361368)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 14, 21, 52, 7, 360371)),
        ),
    ]
