# Generated by Django 3.1.3 on 2022-03-13 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0022_auto_20220304_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 13, 20, 54, 30, 515363)),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 13, 20, 54, 30, 515363)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 13, 20, 54, 30, 515363)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 13, 20, 54, 30, 515363)),
        ),
    ]
