# Generated by Django 3.1.3 on 2022-03-14 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0023_auto_20220313_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointdate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 9, 28, 58, 237407)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 9, 28, 58, 237407)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 9, 28, 58, 237407)),
        ),
    ]
