# Generated by Django 3.1.3 on 2022-04-19 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0025_auto_20220315_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile',
            field=models.CharField(default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 19, 14, 7, 7, 411306)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 19, 14, 7, 7, 410274)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 19, 14, 7, 7, 410274)),
        ),
    ]
