# Generated by Django 3.1.3 on 2022-04-20 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0027_auto_20220419_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='apptime',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 13, 41, 11, 231328)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 13, 41, 11, 231328)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 13, 41, 11, 230324)),
        ),
        migrations.AlterUniqueTogether(
            name='appoint',
            unique_together={('doctor', 'patient', 'appointdate', 'appointtime')},
        ),
    ]
