# Generated by Django 3.1.3 on 2022-04-20 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0032_auto_20220420_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 21, 5, 2, 355571)),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='apptime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 21, 5, 2, 355571)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 21, 5, 2, 354571)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 21, 5, 2, 354571)),
        ),
    ]
