# Generated by Django 3.1.3 on 2022-04-20 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0034_auto_20220420_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 21, 12, 15, 664639)),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='apptime',
            field=models.TimeField(default=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 21, 12, 15, 663641)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 20, 21, 12, 15, 663641)),
        ),
    ]
