# Generated by Django 3.1.3 on 2022-04-21 01:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0035_auto_20220420_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='apptime',
        ),
        migrations.AddField(
            model_name='appoint',
            name='appointtime2',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 21, 8, 43, 31, 20001)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 21, 8, 43, 31, 18969)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 21, 8, 43, 31, 18969)),
        ),
    ]
