# Generated by Django 3.1.3 on 2022-04-25 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0050_auto_20220425_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 12, 43, 46, 338189)),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='approved',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 12, 43, 46, 338189)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 12, 43, 46, 337191)),
        ),
    ]
