# Generated by Django 3.1.3 on 2022-04-25 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0052_auto_20220425_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 12, 48, 30, 309916)),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='approved',
            field=models.BooleanField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 12, 48, 30, 308885)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 12, 48, 30, 308885)),
        ),
    ]
