# Generated by Django 3.1.3 on 2022-04-25 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0055_auto_20220425_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 12, 58, 54, 315582)),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 12, 58, 54, 314583)),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile',
            field=models.CharField(default='patient', max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 12, 58, 54, 314583)),
        ),
    ]
