# Generated by Django 3.1.3 on 2022-04-25 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0068_auto_20220425_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoint',
            name='apptime',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 14, 28, 57, 398137)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msgdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 14, 28, 57, 398137)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 25, 14, 28, 57, 398137)),
        ),
    ]
