# Generated by Django 3.1.3 on 2022-04-27 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0073_auto_20220426_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='login',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 12, 36, 26, 54491)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 12, 36, 26, 54491)),
        ),
    ]
