# Generated by Django 3.1.3 on 2022-04-27 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0075_auto_20220427_1243'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_user',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 12, 44, 7, 806433)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 12, 44, 7, 806433)),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('login', 'password'), name='unique_user'),
        ),
    ]
