# Generated by Django 3.1.3 on 2022-04-27 07:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0076_auto_20220427_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='doc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='MySite.person'),
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 14, 17, 4, 472651)),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 14, 17, 4, 472651)),
        ),
    ]
