# Generated by Django 3.1.3 on 2022-04-27 11:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0084_auto_20220427_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 18, 9, 32, 874244)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='userid',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='MySite.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 18, 9, 32, 874244)),
        ),
    ]
