# Generated by Django 3.1.3 on 2022-04-27 11:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0090_auto_20220427_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appoint',
            name='appointreg',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 18, 36, 54, 473156)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MySite.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='registered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 27, 18, 36, 54, 473156)),
        ),
    ]
